### ISSUE TITLE
Question about availability of REST or webService interface

### ISSUE THREAD

**Issue by dmfranko** [evergreen-library-system/Evergreen#38]
Hello,

It looks like the developer mailing list is dead, or maybe it's somewhere I'm missing it, but I'd like to know if there's a REST or some webService interface available for Evergreen.  I'm more than happy to post this query in a more appropriate place if there is one.

Thanks!
Dan

**Comment by gmcharlt** [comment]
The developer mailing list is very much alive. See http://libmail.georgialibraries.org/mailman/listinfo/open-ils-dev to subscribe to it or check its archives.

Another forum to use is the #evergreen IRC channel on Freenode.
